version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3615
      MYSQL_DATABASE: wp
      MYSQL_PASSWORD: 3615

  wordpress:
      depends_on:
          - db
      image: wordpress:latest
      volumes:
          - wp_volume:/var/www/html
      ports:
          - "8888:80"
      restart: always
      environment: 
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_PASSWORD: 3615

volumes:
    db_volume:
    wp_volume: